name: Get version

on:
  # reusable workflow
  workflow_call:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
    outputs:
      version:
        description: "API_VERSION defined in settings_base.py (with 'v' prefix)"
        value: ${{ jobs.get-version.outputs.version }}
      version-plain:
        description: "API_VERSION defined in settings_base.py"
        value: ${{ jobs.get-version.outputs.version-plain }}
      version-clean:
        description: "API_VERSION defined in settings_base.py (without 'v' prefix or -.* suffix)"
        value: ${{ jobs.get-version.outputs.version-clean }}
      version-suffix:
        description: "API_VERSION after the semver version (e.g. -rc1)"
        value: ${{ jobs.get-version.outputs.version-suffix }}
      prev-version-tag:
        description: "Previous version tag"
        value: ${{ jobs.get-version.outputs.prev-version-tag }}
      is-major-release:
        description: "Is this a major release?"
        value: ${{ jobs.get-version.outputs.is-major-release }}
      untagged:
        description: "Is this an unreleased version?"
        value: ${{ jobs.get-version.outputs.untagged }}

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.scrape.outputs.version }}
      version-plain: ${{ steps.scrape.outputs.version-plain }}
      version-clean: ${{ steps.scrape.outputs.version-plain }}
      version-suffix: ${{ steps.scrape.outputs.version-suffix }}
      prev-version-tag: ${{ steps.search.outputs.prev-version-tag }}
      is-major-release: ${{ steps.search.outputs.previous-major-version-tag != steps.search.outputs.prev-version-tag }}
      untagged: ${{ steps.tags.outputs.untagged == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version
        id: scrape
        run: |
          # Extract release version from settings
          API_VERSION=$(cat backend_django/config/settings_base.py | grep "API_VERSION =" | cut -d'"' -f2)
          # Assert version is valid semver
          if ! [[ "$API_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]]; then
              echo "Release version v$API_VERSION is not valid semver"
              exit 1
          fi
          echo "API_VERSION: v$API_VERSION"
          echo "version=v$API_VERSION" >> $GITHUB_OUTPUT
          echo "version-plain=$API_VERSION" >> $GITHUB_OUTPUT
          echo "version-clean=$(echo $API_VERSION | grep -oP '^[0-9]+\.[0-9]+\.[0-9]+' || true)" >> $GITHUB_OUTPUT
          echo "version-suffix=$(echo $API_VERSION | grep -oP '(?<=-).*$' || true)" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ inputs.debug_enabled }}

      - name: Set up tags
        id: tags
        run: |
          # Get a list of all repository tags
          git fetch --tags --force
          # Create our tag if this is a branch rather than a tag
          UNTAGGED=false
          if [ "${{ github.ref_type }}" == "branch" ]; then
            git config --global user.email gg@example.com
            git config --global user.name "GitHub Actions"
            if [ -z $(git tag --list | grep ${{ steps.scrape.outputs.version }}) ]; then
              UNTAGGED=true
            fi          
            git tag ${{ steps.scrape.outputs.version }} || true
          fi
          echo untagged=$UNTAGGED >> $GITHUB_OUTPUT
          
          # Save tag list to a temporary file
          git tag --list > tags.txt
          echo "tags.txt:"
          cat tags.txt
          echo "$GITHUB_OUTPUT:"
          cat $GITHUB_OUTPUT

      - name: Search for previous version tag
        id: search
        run: |
          # Get the previous tag
          python -c "
          import os, re
          with open('tags.txt', 'r') as f:
            tags = f.read().splitlines()
          tags = [tag for tag in tags if re.match(r'^v[0-9]+\.[0-9]+\.[0-9]+(-.+)?$', tag)]
          # split into major, minor, patch, note and sort by each part
          major = lambda s: int(s.split('.')[0])
          minor = lambda s: int(s.split('.')[1])
          patch = lambda s: int(s.split('.')[2].split('-')[0])
          note = lambda s: s.split('.')[2].split('-')[1] if '-' in s.split('.')[2] else ''
          tags.sort(key=lambda s: (major(s[1:]), minor(s), patch(s), note(s)))  # strip 'v' prefix for major
          i = tags.index('v${{ steps.scrape.outputs.version }}')
          if i == 0:
            os.system('echo prev-version-tag= >> $GITHUB_OUTPUT')
          else:
            os.system(f'echo prev-version-tag={tags[i-1]} >> $GITHUB_OUTPUT')
          # Get the previous major version tag
          if i == 0:
            os.system('echo previous-major-version-tag= >> $GITHUB_OUTPUT')
          else:
            major_version = tags[i].split('.')[0]
            prev_ver_tags = [tag for tag in tags if tag.split('.')[0] < major_version]
            if len(prev_ver_tags) == 0:
                os.system('echo previous-major-version-tag= >> $GITHUB_OUTPUT')
            else:
                os.system(f'echo previous-major-version-tag={prev_ver_tags[-1]} >> $GITHUB_OUTPUT')
          "
          cat $GITHUB_OUTPUT
