name: Release

on:
  workflow_call:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
      allow_breaking_changes:
        type: boolean
        description: 'Skip API compatibility check. WARNING: this will allow breaking changes to the API to be released.'
        required: false
        default: false
      dry-run:
        type: boolean
        description: 'Do not actually release the package, just check that it is valid.'
        required: false
        default: false
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
      allow_breaking_changes:
        type: boolean
        description: 'Skip API compatibility check. WARNING: this will allow breaking changes to the API to be released.'
        required: false
        default: false
      dry-run:
        type: boolean
        description: 'Do not actually release the package, just check that it is valid.'
        required: false
        default: false

jobs:
  check-spec:
    uses: ./.github/workflows/check-spec.yml
    secrets: inherit
    with:
        debug_enabled: ${{ inputs.debug_enabled }}
        dry-run: ${{ inputs.dry-run }}
        allow_breaking_changes: ${{ inputs.allow_breaking_changes }}
  publish-package:
    uses: ./.github/workflows/publish-package.yml
    secrets: inherit
    with:
        debug_enabled: ${{ inputs.debug_enabled }}
        dry-run: ${{ inputs.dry-run }}

  issue-release:
    needs:
      - check-spec
      - publish-package
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check ref is semver
        if: ${{ !inputs.dry-run }}
        run: |
          # Assert that the release version matches the branch name
          if ! [[ "${{ github.ref_name }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]]; then
              echo "Release version ${{ github.ref_name }} is not valid semver, expected vMajor.Minor.Patch"
              exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Retrieve clients artifacts
        uses: actions/download-artifact@v4

      - name: Release
        if: ${{ !inputs.dry-run }}
        uses: softprops/action-gh-release@v2
        with:
          files: |
            clients/**
            spec/**
